# serverless.yml

service: lemon-python-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-python-requirements
  - serverless-wsgi

#------------------------------------------------
# Custom
#------------------------------------------------
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

#------------------------------------------------
# Provider
#------------------------------------------------
provider:
  name: aws
  runtime: python3.6

  # you can overwrite defaults here
  memorySize: 128
  timeout: 30
  cfLogs: true
  stage: dev
  region: ap-northeast-2
  profile: lemon

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
